### ISSUE TITLE
App artifacts dont show in MoveApps

### ISSUE THREAD

**Issue by andreakoelzsch** [chlobeau/moveAppHomeRange#2]
Hi Chloe, @chlobeau 

as the your App has worked fine for me locally, I never realised that the output files (artefacts) did not come through in MoveApps. Did you test it there? I had the same issue with another challenge participant yesterday and we could solve it. Please, would you also adapt your code accordingly and submit a new version to MoveApps, so that this can still be included in the packet that I will send to the reviewers? Preferrably today. 

So, the problem is hte following: MoveApps cannot show folders of data in the artefact space. Whenever there is a folder, it gets stuck trying to read it as a file and then simply does not show any artefacts. The solution is to not have any folders in there. This can be achieved by adding all your html files and related folders into a temporary folder that you then zip and write the zip as an artefact in moveApps. Please see the example here: https://github.com/vee-jain/WeeklyKDE-MoveApps/blob/main/RFunction.R 

The imporant rows are 
````
library('zip')
dir.create(targetDirHtmlFiles <- tempdir())
...
mapshot(plots[[i]], url = file.path(targetDirHtmlFiles, paste0("map_", id_track_list$id[[i]], ".html")))
...
zip_file <- appArtifactPath(paste0("map_html_files.zip"))
  zip::zip(zip_file, 
      files = list.files(targetDirHtmlFiles, full.names = TRUE,
                                   pattern="^map_"),
      mode = "cherry-pick")
````

Thanks for your contribution and all the best,
Andrea

**Comment by chlobeau** [comment]
Hi Andrea @andreakoelzsch,

Thanks for flagging the issue and providing a solution. I added in those lines of code and it ran locally. Won't be able to check in MoveApps until the new version is approved (and it's a Canadian holiday so I'll be offline until this evening). Hopefully everything works for the review.

Thank you!!

**Comment by andreakoelzsch** [comment]
Hi Chloe, thanks for working on this during a holiday! I have built the new App version, but still there are no results shown. This might be due to a small typing error that I have indicated in a Pull request here. Please submit yet another version, hopefull this will finally get the APp to run correctly. Thanks!

**Comment by andreakoelzsch** [comment]
Hi Chloe, thanks for your new version! Finally, there are some artefacts popping up for me, great! The kud area and p95 files look good. However, the zip with html files is empty. Can that be due to the data? Or some typo in the zip adaption? I have shared you a test workflow on MoveApps. Please can you test it out? More tomorrow

**Comment by chlobeau** [comment]
Ok, should be fixed now! Thank you for the support.

**Comment by andreakoelzsch** [comment]
Hi @chlobeau .The App works now on MoveApps :) Merci
