### ISSUE TITLE
Extent error

### ISSUE THREAD

**Issue by sarahcd** [chlobeau/moveAppHomeRange#4]
Hi Chloe! I've tried a variety of input and settings but always get this error:
"ERROR:  Error in getverticeshr.estUD(X[[i]], ...): The grid is too small to allow the estimation of home-range.\nYou should rerun kernelUD with a larger extent parameter\n"

The app has no setting for the "extent" argument in [kernelUD](https://rdrr.io/cran/adehabitatHR/man/kernelUD.html). My best guess was to try reducing the "Percent" setting but it didn't help.

* Is there a solution for this? How is the extent chosen when the app runs?
* Is it possible to add a setting to change the extent?
* Even in the best case, users will sometimes get this error. Users need guidance to know what to do and be confident the app works. [See here](https://github.com/movestore/dynBrownianBridge?tab=readme-ov-file#occurrence-distribution-dynamic-brownian-bridge) for what we wrote for another app.

**Comment by chlobeau** [comment]
Hi Sarah! Did you try changing the resolution setting? If so, did that change anything? From there, I can go about troubleshooting, changing settings, error guidance etc. Thanks for letting me know.

**Comment by sarahcd** [comment]
Yes, I tried the resolution. Looking for a replicable example using public data so I can share it....will post back here as soon as I do.

**Comment by chlobeau** [comment]
Hi Sarah, 

Looks like I just got the workflow, thank you! Will try to get it sorted this week and I'll keep you in the loop. 

Cheers,
Chloe

**Comment by sarahcd** [comment]
Ok I got a workflow that reproduces this error and am sharing it with you. It may have to do with characteristics of the input data, in this case with your feedback I can suggest some wording to help users understand what to try. I'll also try some more exploration to assess this but want to share now in case I fix the problem!

With settings 95/200 and 80/2000 I get the original error described:
```
Error in getverticeshr.estUD(X[[i]], ...): The grid is too small to allow the estimation of home-range.
You should rerun kernelUD with a larger extent parameter
```

With settings 80/20000 I get this error:
```
ERROR: ./start-process.sh: line 9:   308 Killed
```

Also: I was away for an hour after seeing this error and before I could share the workflow with you. When I returned and checked the log again, the error had changed to this:
```
Error: The App is out of memory and had to be stopped. This might have been caused by a too large input data set. Try subsetting your data.
```

**Comment by chlobeau** [comment]
Hi Sarah,

I updated the app and it works now with documentation to guide users on how to increase the extent. I also updated the README to include Common Error messages and solutions which includes a guide for ERROR: ./start-process.sh: line 9:   308 Killed, and Error in getverticeshr.estUD(X[[i]], ...). Thanks so much for helping me debug, it's great to have other folks using the app to improve it!

Chloe

**Comment by chlobeau** [comment]
Hello! I updated the app to have an extent parameter and updated the README to include common errors:

ERROR: “Error in getverticeshr.estUD(X[[i]], ...): The grid is too small to allow the estimation of home-range.
You should rerun kernelUD with a larger extent parameter”. SOLUTION Gradually increase the value of the extent parameter until you no longer receive this error.

and ERROR: ./start-process.sh: line 9: 308 Killed: This error likely arises from the resolution (grid size) being unreasonably large to estimate the UD raster (i.e. 20,000 m [20 km]). SOLUTION Reduce the res value until you no longer receive this error.

Thank you so much for helping me debug. It's great to have other folks using the app to improve it.

Chloe

**Comment by sarahcd** [comment]
Thanks a lot Chloe! I'm still getting the 'grid too small' error, even using extent 40000. I'll share this version of the workflow in a second. I think there are no clear units on this but am not sure what is the upper limit of reasonable values. I'd like to get this example to work with 95% and adding 2 animals that move farther than the others (YL188 and YL189) that I removed for now in case those longer-distance movements aren't appropriate to use here. I tried lower and higher values of all the settings but here is the latest:

     2024-04-10 15:53:38.971 INFO : app will be started with configuration:
     2024-04-10 15:53:38.972 INFO : {
     2024-04-10 15:53:38.972 INFO :   "ext": 40000,
     2024-04-10 15:53:38.972 INFO :   "percent": 75,
     2024-04-10 15:53:38.972 INFO :   "res": 200
     2024-04-10 15:53:38.972 INFO : }
     2024-04-10 15:53:41.488 INFO : [1] "ERROR:  Error in getverticeshr.estUD(X[[i]], ...): The grid is too small to allow the estimation of home-range.\nYou should rerun kernelUD with a larger extent parameter\n"

**Comment by chlobeau** [comment]
Hi Sarah, I haven't run it with an extent greater than 10. The app runs for me at percent 75, res 200, ext 1. Apologies in advance for this is a very silly question, but did you update the app?

**Comment by sarahcd** [comment]
Oh I had updated it (updates are really visible on MoveApps and it's 1 click to install)---it was probably just my absurd ext values causing the problem. By upping the extent in increments of 1 I am getting it to work now.

Would it be ok if I send a PR to add a note about how to use the extent setting? I'll also dig into the output and see if there is any other description I could add.

Thank you!

**Comment by chlobeau** [comment]
Yeah! I've never done a pull request (I embarrassingly had to google it...) but that would be great. Thank you!

Chloe

**Comment by sarahcd** [comment]
Sorry, I also didn't know what they were till recently :) It is mostly straightforward once you know the steps. I'll have a look now...

**Comment by chlobeau** [comment]
Your PR is amazing - the documentation is much improved! Thank you so much.
