### ISSUE TITLE
Error in UseMethod("st_coordinates")

### ISSUE THREAD

**Issue by sarahcd** [chlobeau/moveAppHomeRange#5]
Ran into a different error:
Error in UseMethod("st_coordinates"): no applicable method for 'st_coordinates' applied to an object of class "list"

This error occurred because the input from the previous app was ~empty (passed on as something but not in the expected format; see the workflow I shared 1-2 hours ago). So an error is to be expected, but depending on other cases this error might be expected to occur, maybe it is possible to give a useful message.

**Comment by chlobeau** [comment]
Thanks! I added a information in the logger to guide folks that "Input data must be a move2 object - check that the prior app does not output a list (did you use the split function?)".

**Comment by sarahcd** [comment]
Thank you Chloe! This input was due to an error in the previous app, it shouldn't have output a list and is fixed now.
